### ISSUE TITLE
Implementation issue for hunk attention code

### ISSUE THREAD

**Issue by purezhanghan** [CC2Vec/CC2Vec#1]
Thanks for sharing this implementation.
I notice that this implementation for hunk attention won't get called in later forward process, which differ from the description of the original paper. Is there any reason for that?

relevant codes following:
`self.hunkRNN = HunkRNN(self.embed_size, self.hidden_size)`

**Comment by hvdthong** [comment]
Dear Zhang,

Thank you for your interest in our paper. It seems that the code works fine on my side. The line is simply used to set up a recurrent neural network for the hunk module. Can you please try to rerun the code again. 

Thank you and have a good day.
