### ISSUE TITLE
What is the difference between  bfp_cc2ftr.py and  bfp_PNExtended.py 

### ISSUE THREAD

**Issue by Manas-Embold** [CC2Vec/CC2Vec#3]
Hi 
I am unable to figure out difference between the titled files.
Why two file for Bug fixing patch identification task ?

Why there are no default values for arguments in --predict in file bfp_cc2ftr.py like it is for --train
Sample code in bfp_cc2ftr.py
   ` 
   # Training our model
    parser.add_argument('-train', action='store_true', help='training attention model')

    parser.add_argument('-train_data', type=str, default='./data/bfp/train.pkl', help='the directory of our training data')
    parser.add_argument('-test_data', type=str, default='./data/bfp/test.pkl', help='the directory of our testing data')
    parser.add_argument('-dictionary_data', type=str, default='./data/bfp/dict.pkl', help='the directory of our dicitonary data')

    # Predicting our data
    parser.add_argument('-predict', action='store_true', help='extracting features')
    parser.add_argument('-predict_data', type=str, help='the directory of our extracting data')
    parser.add_argument('-name', type=str, help='name of our output file')

    # Predicting our data
    parser.add_argument('-load_model', type=str, default=None, help='loading our model')`

Due to this, when i apply predict with the default model provided with data, i get following error.

>  python bfp_cc2ftr.py -predict -predict_data "data/bfp/test.pkl" -dictionary_data "/content/data/bfp/dict.pkl" -load_model "/content/model/bfp/pn_extend.pt" -name "feature"

Am I passing wrong arguments ?

`Traceback (most recent call last):
  File "bfp_cc2ftr.py", line 92, in <module>
    extracted_cc2ftr(data=data, params=params)
  File "/content/bfp_cc2ftr_extracted.py", line 22, in extracted_cc2ftr
    model.load_state_dict(torch.load(params.load_model))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for HierachicalRNN:
	Missing key(s) in state_dict: "wordRNN.embed.weight", "wordRNN.wordRNN.weight_ih_l0", "wordRNN.wordRNN.weight_hh_l0", "wordRNN.wordRNN.bias_ih_l0", "wordRNN.wordRNN.bias_hh_l0", "wordRNN.wordRNN.weight_ih_l0_reverse", "wordRNN.wordRNN.weight_hh_l0_reverse", "wordRNN.wordRNN.bias_ih_l0_reverse", "wordRNN.wordRNN.bias_hh_l0_reverse", "wordRNN.wordattn.weight", "wordRNN.wordattn.bias", "wordRNN.attn_combine.weight", "sentRNN.sentRNN.weight_ih_l0", "sentRNN.sentRNN.weight_hh_l0", "sentRNN.sentRNN.bias_ih_l0", "sentRNN.sentRNN.bias_hh_l0", "sentRNN.sentRNN.weight_ih_l0_reverse", "sentRNN.sentRNN.weight_hh_l0_reverse", "sentRNN.sentRNN.bias_ih_l0_reverse", "sentRNN.sentRNN.bias_hh_l0_reverse", "sentRNN.sentattn.weight", "sentRNN.sentattn.bias", "sentRNN.attn_combine.weight", "hunkRNN.hunkRNN.weight_ih_l0", "hunkRNN.hunkRNN.weight_hh_l0", "hunkRNN.hunkRNN.bias_ih_l0", "hunkRNN.hunkRNN.bias_hh_l0", "hunkRNN.hunkRNN.weight_ih_l0_reverse", "hunkRNN.hunkRNN.weight_hh_l0_reverse", "hunkRNN.hunkRNN.bias_ih_l0_reverse", "hunkRNN.hunkRNN.bias_hh_l0_reverse", "hunkRNN.hunkattn.weight", "hunkRNN.hunkattn.bias", "hunkRNN.attn_combine.weight", "standard_nn_layer.weight", "standard_nn_layer.bias", "W_nn_tensor_one.weight", "W_nn_tensor_one.bias", "W_nn_tensor_two.weight", "W_nn_tensor_two.bias", "V_nn_tensor.weight", "V_nn_tensor.bias". 
	Unexpected key(s) in state_dict: "embed_msg.weight", "convs_msg.0.weight", "convs_msg.0.bias", "convs_msg.1.weight", "convs_msg.1.bias", "embed_code.weight", "convs_code_line.0.weight", "convs_code_line.0.bias", "convs_code_line.1.weight", "convs_code_line.1.bias", "convs_code_hunk.0.weight", "convs_code_hunk.0.bias", "convs_code_hunk.1.weight", "convs_code_hunk.1.bias". 
	size mismatch for fc1.weight: copying a param with shape torch.Size([128, 404]) from checkpoint, the shape in current model is torch.Size([512, 84]).
	size mismatch for fc1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for fc2.weight: copying a param with shape torch.Size([1, 128]) from checkpoint, the shape in current model is torch.Size([4808, 512]).
	size mismatch for fc2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([4808]).
`

**Comment by hvdthong** [comment]
Hello, 

The "bfp_cc2ftr.py" is used to train the vector representation for the code changes while "bfp_PNExtended.py" is employed to predict the bug fixing patches in the Linux kernel. The code runs fine on my side. Can you please recheck your steps to make sure it follows the readme file? 
Thank you and have a good day.

**Comment by Manas-Embold** [comment]
Thank you for the explanation
The code is working fine now.

Just to confirm, what is the intended name of ouput file of following line
Is it the feature vecor namely "openstack_train_cc2ftr.pkl" and openstack_test_cc2ftr.pkl or something else.
>python lmg_cc2ftr.py -predict -pred_data [path of our data] -dictionary_data [path of our dictionary data] -load_model [path of our model] -name [name of our output file]
