### ISSUE TITLE
Explaination for the data for task : Bug fixing patch identification

### ISSUE THREAD

**Issue by Manas-Embold** [CC2Vec/CC2Vec#4]
I was looking at structure of data
Need to know, explanation for fields in data (schema) specially the meaning of "stable" parameter.
Is it a sort of label to training data ?

and how do we generate our own dataset from github and preprocessing steps, (Added code and Removed Code appears to be encoded / transformed)

`import pickle
train_data = pickle.load(open("/content/data+model/data/bfp/train.pkl", 'rb'))
train_data[0]`

{'code': [{0: 'drivers/md/dm-thin.c',
   'added': {1: ['Normal:TIdent,TPtrOp,TIdent,TAssign,TIdent,TPtVirg']},
   'removed': {2: ['Normal:TIdent,TPtrOp,TIdent,TAssign,TIdent,TPtrOp,TIdent,TDot,TIdent,TPtVirg']}}],
 'date': '1348699539',
 'id': '307615a26e95406c42c95916a66ba50434567e0f',
 'msg': 'thin,set,thin,pool,target,claim,support,zero,discard,data,area,turn,incorrect,process,discard,exact,cover,complet,number,block,target,must,alway,set,thin,pool,target,zero,block,alloc,featur,specifi,block,layer,may,send,discard,onli,part,cover,block,thin,pool,block,partial,discard,guarante,discard,data,get,zero,befor,access,due,thin,devic,cannot,claim,discard,alway,zero,data',
 'stable': 'true'}

**Comment by hvdthong** [comment]
Hello, 

The "stable" parameter indicates the label of the training data. Added code and removed code indicate the '+' and '-' lines respectively in our commits. Thank you and have a good day.

**Comment by Manas-Embold** [comment]
Thank you.

and are the added and removed lines encoded / transformed by some tokenizer during some preprocessing step ?

Say for example  any string in source code encodes as "STRING"
any number in source code encoded as "NUMBER"
Any Indentation in source code encoded as "INDENT" (Just giving examples)

Like first line appears to be encoded as TIdent,TPtrOp,TIdent,TAssign,TIdent,TPtVirg

**Comment by yiikou** [comment]
Hi @hvdthong @CC2Vec , could you give a short explanation towards the questions above? Those questions are blockers for reproducing this amazing model on other dataset. Thank you!

**Comment by hvdthong** [comment]
Hi @yiikou , I don't put a parser to encode the code information as it's not general enough. My parser only works on C language (Linux kernel) but not for the other languages (i.e., Java, Python, etc.). Thank you and have a good day.

**Comment by yiikou** [comment]
Hi @hvdthong , thanks for the explanation. Can it explain the reason why the code data in QT data set is not parsed, while in patchnet dataset is parsed?

Thank you.

**Comment by maramassi** [comment]
Hi @hvdthong, I understand that your parser is not generic. But would you able be to share with us what are the necessary pre-processing steps to do? For example replacing literals, function names, etc... so we can generate our own parser for Bug fixing patch identification and Just-in-Time Defect Prediction?
