### ISSUE TITLE
Please help with Expected Input and Output For JIT Task

### ISSUE THREAD

**Issue by Manas-Embold** [CC2Vec/CC2Vec#5]
Hi,
I need to understand what input a script expects and what output file it produces (with extension of file) for JIT task.

1. **jit_cc2ftr.py --train** ==> This script trains model to learn how to represent code changes as features. (Please Correct me if i am understanding it wrong)
    Expects following:
    1. **-train_data** [path of our training data] ==> Expects **/data+model/data/jit/openstack_train.pkl**
    2. **-test_data** [path of our training data]  ==> Expects **/data+model/data/jit/openstack_test.pkl**
    3. **-dictionary_data** [path of our dictionary data] ==> Expects **/data+model/data/jit/openstack_dict.pkl**

**Question:** 
1. Are we training model to learn feature vector from code change ?
2. If we have out own data, how do we generate our own dictionary file.
3. Whats the output ? => A Model in Snapshot Directory ?

2. **jit_cc2ftr.py -predict**
       Expects following:
        1. **-predict -predict_data** [path of our data] ==> What data it expects data+model/data/jit/openstack_test.pkl ? or feature vector please specify.
         2. **-dictionary_data** [path of our dictionary data] ==> Referring to data+model/data/jit/openstack_dict.pkl ? or something else.
         3. **-load_model** [path of our model] ==> Referring to model saved in Snapshot directory from Previous Step (jit_cc2ftr.py --train)? or something else 
         4. **-name** [name of our output file] ==> What is the extension / format of this output file, what does it represent, what kind of prediction this is ? Is it classification or just the feature vector from code change ?

==============================================================================

3. **jit_DExtended.py -train**
       Expects Following:
       1. **-train_data** [path of our data] ==> This is referring to /data+model/data/jit/openstack_train.pkl Right ?
       2. **-train_data_cc2ftr** [path of our code changes features extracted from training data] ==> This is refering to data+model/data/jit/openstack_train_cc2ftr.pkl Right ? How do we obtain this cc2ftr file, is it obtained from output of previous step (jit_cc2ftr.py -predict -name** [name of our output file] ) ?
       3. **-dictionary_data** [path of our dictionary data] ==> This is referring to /data+model/data/jit/openstack_dict.pkl Right ?

Question:
Where does it produce trained model and with what name.

4. **jit_DExtended.py -predict**
       Expects following:
       1. **-pred_data** [path of our data]
       2. **-pred_data_cc2ftr** [path of our code changes features extracted from our data] ==> In which step these are extracted.
       3. **-dictionary_data** [path of our dictionary data]
       4. **-load_model** [path of our model] ==> Model produced from previous step (jit_DExtended.py -train) ?

I would be thankful, if you can include the details in Read me file itself.
Please excuse, for simple questions.

**Comment by Manas-Embold** [comment]
I have gone through entire code, and was able to understand expected input and outputs.
However, i would suggest its good to add the same in readme file.

**Comment by Manas-Embold** [comment]
Re Opening for authors comments

**Comment by hvdthong** [comment]
Many thanks for your suggestion. I'll update the README file. At this moment, I'm very busy as I have some deadlines which are coming. Thank you again for the nice suggestion.

**Comment by yiikou** [comment]
Dear @Manas-Embold , your questions are valuable for reproduce the experiment. May I ask you to give very simple or short answers of them? Especially for the dictionary related questions. Thank you!
