### ISSUE TITLE
Lines Added and Lines Removed missing in openstack_train_dextend.pkl and openstack_test_dextend.pkl

### ISSUE THREAD

**Issue by Manas-Embold** [CC2Vec/CC2Vec#6]
Hi

I was looking at subjected data for JIT DeExtended task

>data = pickle.load(open('/content/data+model/data/jit/openstack_test_dextend.pkl', 'rb'))
>ids, labels, msgs, codes = data
>ids[0:2], labels[0:2], msgs[0:2], codes[0:2]

OUTPUT for two rows

`(['844a228c3c42dac802a82510eb17fcfaccb0e1f8',
  '37627645e47d35643454a84ae4a8c682ee0b18eb'],
 [0, 0],

 ['remove unused local vars remove unused local vars in test files to make code cleaner . change-id : if97fad2d6b85730ea1cebc477f5f092c1c17976d',
  'move nvp db extensions under dbexts module . small clean-up to the plugin directory . this is also more in line with how api extensions have their own module . change-id : idae52e30128f4ed9f8f7f5164991952bc3189f53'],

 [['added _ code removed _ code',
   'added _ code removed _ code',
   'added _ code removed _ code',
   'added _ code removed _ code',
   'added _ code removed _ code',
   'added _ code removed _ code',
   'added _ code removed _ code'],
  ['added _ code removed _ code',
   'added _ code removed _ code',
   'added _ code removed _ code',
   'added _ code removed _ code',
   'added _ code removed _ code',
   'added _ code removed _ code']])`

As you can see, actual lines added and actual lines removed are missing from pickle.
Is it expected the same way ?
or should we use openstack_train.pkl and openstack_test.pkl instead of openstack_train_dextend.pkl and openstack_test_dextend.pkl

**Comment by hvdthong** [comment]
Hmm, it's quite weird to me as well. I need to take a look at the dataset to understand why. Many thanks for the useful comment.

**Comment by Manas-Embold** [comment]
I think we can use openstack_train.pkl  in place of openstack_train_dextend.pkl
and openstack_test.pkl  instead of openstack_test_dextend.pkl 

Since openstack_train.pkl and openstack_test.pkl  contains added and removed code.

**Comment by hvdthong** [comment]
Many thanks for your comment. Actually, we can't use the openstack_train.pkl and openstack_test.pkl as the added code and removed code are separated. The model of JIT task takes input as the mixing between the added code and removed code. That's why I have two separate datasets for this task.

**Comment by yiikou** [comment]
Hi @hvdthong , I checked qt_train_dextend.pkl and it looks also lack some information. Or it is normal?

Btw, I downloaded data from https://zenodo.org/record/3965149#.X--Y9-lKjIH.

**Comment by hvdthong** [comment]
Hi @yiikou , many thanks for your interest in our tool. I think qt_train_dextend.pkl lacks the code information. I'll reupload the dataset. Thank you and have a great day.

**Comment by yiikou** [comment]
Hi @hvdthong , thanks for the reply. After checking deepjit paper, I found that it mix added and removed code line. So I simply merge the added_code and removed_code in the qt_train.pkl to generate code data in qt_train_dextend.pkl. Is it a correct or not?

**Comment by junkgear** [comment]
Hi @yiikou 
Can you share the code / function you used to merge added and removed code.
I have been waiting for over a month now for correct dataset.
If your trick of merging works that would be super helpful.
P.S This is manas with another account.

**Comment by yiikou** [comment]
@junkgear I simply extract code data from the qt_train.pkl, and simply use ``" ".join`` to merge the values of "added_code" and "removed_code" keys. I'm extracting cc2ftr and haven't tested it. Will update whether it works or not here.

**Comment by Manas-Embold** [comment]
Hi Joe,
Can you share entire function, how you iterated over the .pkl file and used `" ".join`.
as there are multiple level in list of list structure, its confusing.
Thanks

**Comment by yiikou** [comment]
Hi Manas, due to some limitation I cannot share my code. My the idea is pretty simple, just iterate each file-level key, and extract the value of "added_code" and "removed_code", append them to the same list, and then further append the list to the commit-level list. Hope it could help you.
