### ISSUE TITLE
padding_commit_file() function not called for Jit_DeExtended task, but called in Jit_cc2ftr task

### ISSUE THREAD

**Issue by Manas-Embold** [CC2Vec/CC2Vec#7]
Hi
I want to understand, why  **padding_commit_file()** function was called for Jit_cct2ftr but not for Jit_DeExtended.

Here, in function padding_commit_code(), we called three functions namely padding_commit_code_length(), padding_commit_code_line() and **padding_commit_file()**
https://github.com/CC2Vec/CC2Vec/blob/master/jit_padding.py#L100

But, here in Jit_DeExtended task only two function called padding_commit_code_length(), padding_commit_code_line() but **padding_commit_file()** is skipped.
https://github.com/CC2Vec/CC2Vec/blob/master/jit_DExtended_padding.py#L60

**Comment by hvdthong** [comment]
We don't need padding_commit_file as all the files for each commit are concatenated. Thank you.
