### ISSUE TITLE
clean_and_reformat_code() not called for JitExtended but called for Jit_cc2ftr

### ISSUE THREAD

**Issue by Manas-Embold** [CC2Vec/CC2Vec#8]
Hi,

I want to understand, why 'code' in 'openstack_test_dextend.pkl' was not divided into added and removed code before padding and converting to numerical format as done for 'code' in 'openstack_train.pkl'

Here code divided into added and removed before padding
https://github.com/CC2Vec/CC2Vec/blob/master/jit_cc2ftr.py#L72

Here code not divided into added and removed before padding
https://github.com/CC2Vec/CC2Vec/blob/master/jit_DExtended.py#L62

**Comment by Manas-Embold** [comment]
What kind and format of 'code' does jit_DExtended expects.

**Comment by hvdthong** [comment]
The code includes a list of lists. Each list contains a list of mixing added and removed lines.

**Comment by Manas-Embold** [comment]
Hi Thong,
Any thoughts on how do i convert dataset from 'openstack_train.pkl' to 'openstack_test_dextend.pkl' format
Can you guide me to function / code which does the job or you might have used to convert the same.

**Comment by yiikou** [comment]
Hi @Manas-Embold and @hvdthong , could you post or mention the function/code that does the conversion job here?

**Comment by hvdthong** [comment]
The 'openstack_train.pkl' to 'openstack_test_dextend.pkl' are different. I haven't written a function to convert the two datasets.
