### ISSUE TITLE
About reproducing the result of Task 1 (Log Message Generation)

### ISSUE THREAD

**Issue by KAIST-JongchanPark** [CC2Vec/CC2Vec#9]
Thanks for providing your implementation.

I tried to reproduce the result of Task 1 in your paper, but I have some problems.

1. During evaluation in Task 1, I found some issue in implementation of [finding_bestK()](https://github.com/CC2Vec/CC2Vec/blob/6e519620a85306855a2d360eff751852c9e4a37a/lmg_eval.py#L24), lmg_eval.py
```
def finding_bestK(diff_trains, diff_test, topK_index):
    if topK_index == None:        
        diff_code_train = [d.lower().split() for d in diff_trains]
    else:
        diff_code_train = get_data_index(data=diff_trains, indexes=topK_index)
        diff_code_train = [d.lower().split() for d in diff_code_train]

    diff_code_test = diff_test.lower().split()
    chencherry = SmoothingFunction()
    scores = [sentence_bleu(references=[diff_code_test], hypothesis=d, smoothing_function=chencherry.method1) for d in
            diff_code_train]
    bestK = scores.index(max(scores))
    
    return bestK
```

This function returns "bestK" which means the index of best BLEU score log msg in "scores". 
```
def get_data_index(data, indexes):
    return [data[i] for i in indexes]
```

However, due to [get_data_index()](https://github.com/CC2Vec/CC2Vec/blob/6e519620a85306855a2d360eff751852c9e4a37a/lmg_eval.py#L20), index number is changed so that index of "diff_trains"(original) and "scores"(changed) don't match any more, and it causes wrong choice of log msg.

My suggestion is, [finding_bestK()](https://github.com/CC2Vec/CC2Vec/blob/6e519620a85306855a2d360eff751852c9e4a37a/lmg_eval.py#L24) should be
```
return topK_index[bestK]
```
for correct index with original one.

2. In the paper or this github, there is no mention about topK for [load_kNN_model()](https://github.com/CC2Vec/CC2Vec/blob/6e519620a85306855a2d360eff751852c9e4a37a/lmg_eval.py#L48)
```
def load_kNN_model(org_diff_code, tf_diff_code, ref_msg, topK=None):
    org_diff_train, org_diff_test = org_diff_code
    tf_diff_train, tf_diff_test = tf_diff_code
    ref_train, ref_test = ref_msg
    blue_scores = list()  

    run_tqdm = [i for i in range(tf_diff_test.shape[0])]  
    
    for i, (_) in enumerate(tqdm(run_tqdm)):   
        element = tf_diff_test[i, :]
        element = np.reshape(element, (1, element.shape[0]))
        cosine_sim = cosine_similarity(X=tf_diff_train, Y=element)

        if topK == None:
            bestK = finding_bestK(diff_trains=org_diff_train, diff_test=org_diff_test[i], topK_index=topK)
        else:
            topK_index = finding_topK(cosine_sim=cosine_sim, topK=topK)
            bestK = finding_bestK(diff_trains=org_diff_train, diff_test=org_diff_test[i], topK_index=topK_index)
        train_msg, test_msg = ref_train[bestK].lower(), ref_test[i].lower()        

        chencherry = SmoothingFunction()
        blue_score = sentence_bleu(references=[test_msg.split()], hypothesis=train_msg.split(), 
                                   smoothing_function=chencherry.method5)
        blue_scores.append(blue_score)    
    return blue_scores 
```
(I used modified [finding_bestK()](https://github.com/CC2Vec/CC2Vec/blob/6e519620a85306855a2d360eff751852c9e4a37a/lmg_eval.py#L24))

First, I tried to use default value for topK, "None" and I realized that "None" value doesn't use "cosine_sim" value during evaluation due to if condition, which, I think, should have been used for prediction. I got 20.58 BLEU score with "None" topK value, and I think it is upper bound BLEU score for this experiment because it compares all possible cases when topK is "None" and returns best BLEU score case.

Then, I tried to use different values for topK (5, 2000, 5000, 10000). Case 5 results too low BLEU score, about 2.2. (20.48 in paper) Case 2000, 5000, 10000 result little higher score, 9.72, 12.16, 14.32 for each case, which are still lower than 20.48.

Could you comment more in detail?

**Comment by CC2Vec** [comment]
Hi KAIST-JongchanPark, 

Thank you for your comment. I think in my old code, I run different topK values (until 20,000) and selected the best topK values. Actually, I don't remember which topK value was chosen during the evaluation. 

Many thanks in advance and have a great day.

**Comment by VicenTYC** [comment]
I have the same question, when using the "cosine_sim" value during evaluation, as you said, the final topK=20000, BLEU score does not increase linearly, only 1.82. So can you repeat this experiment and provide a final reliable topK value or more detail?
BTW, I modified the method "finding_bestK()" as well as KAIST-JongchanPark.

**Comment by CC2Vec** [comment]
Thank you for your question. Let me try to work on it. I have no longer working on this project but I'll try to spend my time to clarify this problem. 

Thank you again and have a great day.
